/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;
import java.util.Date;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import Codigo.clsRegistro;
import java.util.*;
import java.util.Random;
import javax.swing.DefaultComboBoxModel;
/**
 *
 * @author Juan Pablo Tovar M
 */
public class frm_Registro extends javax.swing.JFrame {
        LinkedList<clsRegistro> afectados = new LinkedList<>();
        String Ayudas [][] = new String [1000][4];
        String Español[]= new String[1000];
        String Ingles[]=new String[1000];
        int codigo_R = 0;
        int sw = 0;
        int encuentra = 0;
        int fila = 0;
        java.util.Date fecha = new Date();
        
        
    /**
     * Creates new form frm_Registro
     */
    public frm_Registro() {
        initComponents();
        lblFecha.setText(""+fecha);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblRegistro = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblRequerimientos = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblCodigo = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblApellido = new javax.swing.JLabel();
        lblContacto = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        lblEdad = new javax.swing.JLabel();
        lblSexo = new javax.swing.JLabel();
        lblBarrio = new javax.swing.JLabel();
        txtAfectacionR = new javax.swing.JTextField();
        lblAfectacion = new javax.swing.JLabel();
        lblCantAfectados = new javax.swing.JLabel();
        lblIdentificacion = new javax.swing.JLabel();
        btnNuevoR = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        cbxSexoR = new javax.swing.JComboBox<>();
        txtCantHabitR = new javax.swing.JTextField();
        txtIdentificacionR = new javax.swing.JTextField();
        txtBarrioR = new javax.swing.JTextField();
        txtEdadR = new javax.swing.JTextField();
        txtNombreR = new javax.swing.JTextField();
        txtApellidoR = new javax.swing.JTextField();
        txtContactoR = new javax.swing.JTextField();
        txtCorreoR = new javax.swing.JTextField();
        lblCodigoR = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lblItem = new javax.swing.JLabel();
        lblCode = new javax.swing.JLabel();
        lblTipoAyuda = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        btnNewA = new javax.swing.JButton();
        btnSaveA = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        lblMensajeAyudas = new javax.swing.JLabel();
        txtItemA = new javax.swing.JTextField();
        txtCodeA = new javax.swing.JTextField();
        cbxTipoAyudaA = new javax.swing.JComboBox<>();
        lblColocarFecha = new javax.swing.JLabel();
        lblAyudas = new javax.swing.JLabel();
        cbxIdioma = new javax.swing.JComboBox<>();
        btnCambiarIdioma = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(19, 19, 19));

        jPanel2.setBackground(new java.awt.Color(43, 43, 43));

        lblRegistro.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 36)); // NOI18N
        lblRegistro.setForeground(new java.awt.Color(134, 134, 139));
        lblRegistro.setText("Registro afectados ola invernal.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRegistro)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRegistro)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(19, 19, 19));

        lblRequerimientos.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        lblRequerimientos.setForeground(new java.awt.Color(134, 134, 139));
        lblRequerimientos.setText("Requerimientos:");

        jPanel4.setBackground(new java.awt.Color(43, 43, 43));

        lblCodigo.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        lblCodigo.setForeground(new java.awt.Color(134, 134, 139));
        lblCodigo.setText("Codigo:");

        lblNombre.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(134, 134, 139));
        lblNombre.setText("Nombre:");

        lblApellido.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        lblApellido.setForeground(new java.awt.Color(134, 134, 139));
        lblApellido.setText("Apellido:");

        lblContacto.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        lblContacto.setForeground(new java.awt.Color(134, 134, 139));
        lblContacto.setText("Contacto:");

        lblCorreo.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        lblCorreo.setForeground(new java.awt.Color(134, 134, 139));
        lblCorreo.setText("Correo:");

        lblEdad.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        lblEdad.setForeground(new java.awt.Color(134, 134, 139));
        lblEdad.setText("Edad:");

        lblSexo.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        lblSexo.setForeground(new java.awt.Color(134, 134, 139));
        lblSexo.setText("Sexo:");

        lblBarrio.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        lblBarrio.setForeground(new java.awt.Color(134, 134, 139));
        lblBarrio.setText("Barrio:");

        txtAfectacionR.setBackground(new java.awt.Color(43, 43, 43));
        txtAfectacionR.setForeground(new java.awt.Color(134, 134, 139));

        lblAfectacion.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        lblAfectacion.setForeground(new java.awt.Color(134, 134, 139));
        lblAfectacion.setText("Afectación:");

        lblCantAfectados.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        lblCantAfectados.setForeground(new java.awt.Color(134, 134, 139));
        lblCantAfectados.setText("Cantidad de afectados:");

        lblIdentificacion.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        lblIdentificacion.setForeground(new java.awt.Color(134, 134, 139));
        lblIdentificacion.setText("Identificiación:");

        btnNuevoR.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        btnNuevoR.setForeground(new java.awt.Color(21, 97, 240));
        btnNuevoR.setText("Nuevo");
        btnNuevoR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoRActionPerformed(evt);
            }
        });

        btnGuardar.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(21, 97, 240));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnActualizar.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(21, 97, 240));
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnBuscar.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(21, 97, 240));
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        cbxSexoR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar una  opción.", "1.Hombre", "2.Mujer", " " }));

        txtCantHabitR.setBackground(new java.awt.Color(43, 43, 43));
        txtCantHabitR.setForeground(new java.awt.Color(134, 134, 139));

        txtIdentificacionR.setBackground(new java.awt.Color(43, 43, 43));
        txtIdentificacionR.setForeground(new java.awt.Color(134, 134, 139));

        txtBarrioR.setBackground(new java.awt.Color(43, 43, 43));
        txtBarrioR.setForeground(new java.awt.Color(134, 134, 139));

        txtEdadR.setBackground(new java.awt.Color(43, 43, 43));
        txtEdadR.setForeground(new java.awt.Color(134, 134, 139));

        txtNombreR.setBackground(new java.awt.Color(43, 43, 43));
        txtNombreR.setForeground(new java.awt.Color(134, 134, 139));

        txtApellidoR.setBackground(new java.awt.Color(43, 43, 43));
        txtApellidoR.setForeground(new java.awt.Color(134, 134, 139));

        txtContactoR.setBackground(new java.awt.Color(43, 43, 43));
        txtContactoR.setForeground(new java.awt.Color(134, 134, 139));

        txtCorreoR.setBackground(new java.awt.Color(43, 43, 43));
        txtCorreoR.setForeground(new java.awt.Color(134, 134, 139));

        lblCodigoR.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCodigoR.setForeground(new java.awt.Color(21, 97, 240));
        lblCodigoR.setText("0");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblApellido)
                                    .addComponent(lblNombre)
                                    .addComponent(lblCodigo))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtApellidoR, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                                    .addComponent(txtNombreR, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                                    .addComponent(lblCodigoR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(1, 1, 1))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblContacto)
                                    .addComponent(lblCorreo))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtContactoR, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                                    .addComponent(txtCorreoR))))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(lblEdad)
                                        .addGap(3, 3, 3))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(lblSexo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbxSexoR, 0, 419, Short.MAX_VALUE)
                                    .addComponent(txtEdadR)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblAfectacion)
                                    .addComponent(lblCantAfectados)
                                    .addComponent(lblBarrio))
                                .addGap(6, 6, 6)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAfectacionR)
                                    .addComponent(txtCantHabitR)
                                    .addComponent(txtBarrioR)))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(426, 426, 426)
                                .addComponent(lblIdentificacion))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(btnNuevoR)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnGuardar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnActualizar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdentificacionR, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
                        .addGap(1, 1, 1)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCodigo)
                        .addComponent(lblCodigoR))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblEdad)
                        .addComponent(txtEdadR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNombre)
                        .addComponent(txtNombreR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cbxSexoR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSexo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblApellido)
                        .addComponent(txtApellidoR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblBarrio)
                        .addComponent(txtBarrioR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblContacto)
                        .addComponent(txtContactoR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtAfectacionR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblAfectacion)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCorreo)
                            .addComponent(txtCorreoR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCantAfectados)
                        .addComponent(txtCantHabitR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdentificacion)
                    .addComponent(txtIdentificacionR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevoR)
                    .addComponent(btnGuardar)
                    .addComponent(btnActualizar)
                    .addComponent(btnBuscar))
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(43, 43, 43));
        jPanel5.setForeground(new java.awt.Color(43, 43, 43));

        lblItem.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        lblItem.setForeground(new java.awt.Color(134, 134, 139));
        lblItem.setText("Item:");

        lblCode.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        lblCode.setForeground(new java.awt.Color(134, 134, 139));
        lblCode.setText("Codigo:");

        lblTipoAyuda.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        lblTipoAyuda.setForeground(new java.awt.Color(134, 134, 139));
        lblTipoAyuda.setText("Tipo de ayuda:");

        lblFecha.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(134, 134, 139));
        lblFecha.setText("Fecha:");

        btnNewA.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        btnNewA.setForeground(new java.awt.Color(21, 97, 240));
        btnNewA.setText("Nuevo");
        btnNewA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewAActionPerformed(evt);
            }
        });

        btnSaveA.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        btnSaveA.setForeground(new java.awt.Color(21, 97, 240));
        btnSaveA.setText("Guardar");
        btnSaveA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveAActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(134, 134, 139));

        jLabel19.setForeground(new java.awt.Color(19, 19, 19));

        lblMensajeAyudas.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblMensajeAyudas.setForeground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMensajeAyudas)
                    .addComponent(jLabel19))
                .addContainerGap(209, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel19)
                .addGap(30, 30, 30)
                .addComponent(lblMensajeAyudas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtItemA.setBackground(new java.awt.Color(43, 43, 43));
        txtItemA.setForeground(new java.awt.Color(134, 134, 139));
        txtItemA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtItemAActionPerformed(evt);
            }
        });

        txtCodeA.setBackground(new java.awt.Color(43, 43, 43));
        txtCodeA.setForeground(new java.awt.Color(134, 134, 139));

        cbxTipoAyudaA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una ayuda.", "1.Comida.", "2.Aseo.", "3.Electrodomestico.", "4.Monetario." }));

        lblColocarFecha.setForeground(new java.awt.Color(21, 97, 240));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCode)
                            .addComponent(lblItem))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtItemA, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodeA, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblFecha)
                            .addComponent(lblTipoAyuda))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbxTipoAyudaA, 0, 244, Short.MAX_VALUE)
                            .addComponent(lblColocarFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(42, 42, 42)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSaveA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNewA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(42, 65, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtItemA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblItem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCode)
                    .addComponent(btnNewA)
                    .addComponent(txtCodeA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoAyuda)
                    .addComponent(cbxTipoAyudaA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFecha)
                    .addComponent(btnSaveA)
                    .addComponent(lblColocarFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblAyudas.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        lblAyudas.setForeground(new java.awt.Color(134, 134, 139));
        lblAyudas.setText("Ayudas:");

        cbxIdioma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1. Español.", "2. Ingles." }));
        cbxIdioma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxIdiomaActionPerformed(evt);
            }
        });
        cbxIdioma.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cbxIdiomaKeyReleased(evt);
            }
        });

        btnCambiarIdioma.setText("Cambiar Idioma:");
        btnCambiarIdioma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarIdiomaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lblAyudas)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblRequerimientos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCambiarIdioma)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRequerimientos)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbxIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCambiarIdioma)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAyudas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoRActionPerformed
    txtAfectacionR.setText("");
    txtApellidoR.setText("");
    lblCodigoR.setText("0");
    txtContactoR.setText("");
    txtCorreoR.setText("");
    txtEdadR.setText("");
    txtIdentificacionR.setText("");
    txtNombreR.setText("");
    txtBarrioR.setText("");
    txtCantHabitR.setText("");
    }//GEN-LAST:event_btnNuevoRActionPerformed

    public void fnt_aleatorio (int min, int max){
        Random random = new Random();
        codigo_R = random.nextInt(max + min) + min;
        txtCodeA.setText("" + codigo_R);
        lblCodigoR.setText("" + codigo_R);
}
    public void fnt_aleatorio2 (int min, int max){
        Random random = new Random();
        codigo_R = random.nextInt(max + min) + min;
        txtItemA.setText("" + codigo_R);
}
    
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
    if(txtAfectacionR.getText().equals("")||txtApellidoR.getText().equals("")||txtCantHabitR.getText().equals("")||
            txtContactoR.getText().equals("")||txtCorreoR.getText().equals("")
            ||txtIdentificacionR.getText().equals("")||txtNombreR.getText().equals("")) 
           {
            
        JOptionPane.showMessageDialog(null, "Debe ingresar la información solicitada");
    }else{
        if(Integer.parseInt(txtEdadR.getText())<18){
        JOptionPane.showMessageDialog(null, "No tiene la edad necesaria para realizar");
    }else{
            afectados.add(new clsRegistro(
                    txtNombreR.getText(), 
                    txtApellidoR.getText(), 
                    txtContactoR.getText(), 
                    txtCorreoR.getText(),
                    Integer.parseInt(txtEdadR.getText()),
                    "" + cbxSexoR.getSelectedIndex(), 
                    txtBarrioR.getText(), 
                    txtAfectacionR.getText(), 
                    Integer.parseInt(txtCantHabitR.getText()),
                    txtIdentificacionR.getText()
            ));
            fnt_aleatorio(1, 1000);
            if(cbxIdioma.getSelectedIndex()==1){
               JOptionPane.showMessageDialog(null, "La informacion fue guardada con exito"  + 
                    JOptionPane.INFORMATION_MESSAGE);
            }
            if(cbxIdioma.getSelectedIndex()==2){
                JOptionPane.showMessageDialog(null, "The information was successfully saved");
            }

          }
    }//GEN-LAST:event_btnGuardarActionPerformed
    
}
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        if (txtIdentificacionR.getText().equals("")){
           if(cbxIdioma.getSelectedIndex()==1){
            JOptionPane.showMessageDialog(null, "Debe ingresar dato a buscar",
            "BUSCAR", JOptionPane.ERROR_MESSAGE);
           }
           if(cbxIdioma.getSelectedIndex()==2){
               JOptionPane.showMessageDialog(null, "You must enter data to search");
           }

           txtIdentificacionR.setText("");
             txtIdentificacionR.requestFocus();
       }else{
        for (int i = 0; i <afectados.size(); i++){
            if (txtIdentificacionR.getText().equals(afectados.get(i).getId())){
               sw= 1;
               encuentra = i;
            }
        }
        if (sw == 0){
            btnActualizar.setEnabled(false);
            if(cbxIdioma.getSelectedIndex() == 1){
            JOptionPane.showMessageDialog(null, "La información no se ha registrado o encontrado",
                    "ERROR", JOptionPane.ERROR_MESSAGE);
            }
            if(cbxIdioma.getSelectedIndex()==2){
                JOptionPane.showMessageDialog(null, "The information has not been recorded");
            }
        }else{
            if(cbxIdioma.getSelectedIndex() == 1){
            JOptionPane.showMessageDialog(null, "Se ha encontrado la información con éxito", "BUSCAR",
                  JOptionPane.INFORMATION_MESSAGE);
            }
            if(cbxIdioma.getSelectedIndex() == 2){
                JOptionPane.showMessageDialog(null, "The information was successfully found");
            }

            btnActualizar.setEnabled(true);
            txtApellidoR.setText("" + afectados.get(encuentra).getStrApellido());
            txtBarrioR.setText("" + afectados.get(encuentra).getStrBarrio());
            txtCantHabitR.setText("" + afectados.get(encuentra).getIntCantHabitantes());
            txtContactoR.setText("" + afectados.get(encuentra).getStrContacto());
            txtCorreoR.setText("" + afectados.get(encuentra).getStrcorreo());
            txtEdadR.setText(""+ afectados.get(encuentra).getIntEdad());
            txtIdentificacionR.setText("" + afectados.get(encuentra).getId());
            txtAfectacionR.setText("" + afectados.get(encuentra).getStrAfectacion());
            txtNombreR.setText("" + afectados.get(encuentra).getStrName());
            cbxSexoR.setSelectedItem("" + afectados.get(encuentra).getStrSexo());
            
        }
       }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnCambiarIdiomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarIdiomaActionPerformed
    //Aclaracion: guarde las traducciones en los vectores incorrectos y me dio pereza cambiarlos :V
    if(cbxIdioma.getSelectedIndex()== 2){
        //labels de Requerimientos
        Español[0] = "Code:";lblCodigo.setText("" + Español[0]);
        Español[1] = "Name:";lblNombre.setText("" + Español[1]);
        Español[2] = "Last Name:";lblApellido.setText("" + Español[2]);
        Español[3] = "Contact:";lblContacto.setText("" + Español[3]);
        Español[4] = "Email:";lblCorreo.setText("" + Español[4]);
        Español[5] = "Age:";lblEdad.setText("" + Español[5]);
        Español[6] = "Sex:";lblSexo.setText("" + Español[6]);
        Español[7] = "Neighborhood:";lblBarrio.setText("" + Español[7]);
        Español[8] = "Damages:";lblAfectacion.setText("" + Español[8]);
        Español[9] = "Amount of inhabitants";lblCantAfectados.setText("" + Español[9]);
        Español[9] = "ID:";lblIdentificacion.setText("" + Español[9]);
        //botones de requerimientos
        Español[10] = "New:";btnNuevoR.setText("" + Español[10]);
        Español[11] = "Save:";btnGuardar.setText("" + Español[11]);
        Español[12] = "Update:";btnActualizar.setText("" + Español[12]);
        Español[13] = "Search:";btnBuscar.setText("" + Español[13]);
        //labels de ayuda
        Español[14] = "Code:";lblCode.setText("" + Español[14]);
        Español[15] = "type of support:";lblTipoAyuda.setText("" + Español[15]);
        Español[16] = "Date:";lblFecha.setText("" + Español[16]);
        //botones de ayuda
        Español[17] = "New:";btnNewA.setText("" + Español[17]);
        Español[18] = "Save:";btnSaveA.setText("" + Español[18]);
        Español[19] = "Change laguage";btnCambiarIdioma.setText("" + Español[19]);
        Español[20] = "Affected Registration (Rainstorm desaster)";lblRegistro.setText("" + Español[20]);
        Español[21] = "Supports";lblAyudas.setText("" + Español[21]);
        Español[22] = "Requirements";lblRequerimientos.setText("" + Español[22]);
        //cambiar combobox 
        cbxIdioma.setModel(new DefaultComboBoxModel<>(new String [] {"Choose a language","1.Spanish","2.English"}));
        cbxSexoR.setModel(new DefaultComboBoxModel<>(new String []{"Choose an option","1.Man","2.Woman"}));
        cbxTipoAyudaA.setModel(new DefaultComboBoxModel<>(new String [] {"Select a support","1.Food","2.Cleaning"
        ,"3.Home appliances","4.Monetary"}));
        cbxIdioma.setSelectedIndex(2);
        
        }
    if(cbxIdioma.getSelectedIndex()== 1){
        Ingles[0] = "Codigo:";lblCodigo.setText("" + Ingles[0]);
        Ingles[1] = "Nombre:";lblNombre.setText("" + Ingles[1]);
        Ingles[2] = "Apellido:";lblApellido.setText("" + Ingles[2]);
        Ingles[3] = "Contacto:";lblContacto.setText("" + Ingles[3]);
        Ingles[4] = "Correo:";lblCorreo.setText("" + Ingles[4]);
        Ingles[5] = "Edad:";lblEdad.setText("" + Ingles[5]);
        Ingles[6] = "Sexo:";lblSexo.setText("" + Ingles[6]);
        Ingles[7] = "Barrio:";lblBarrio.setText("" + Ingles[7]);
        Ingles[8] = "Afectacion:";lblAfectacion.setText("" + Ingles[8]);
        Ingles[9] = "Cantidad de afectados:";lblCantAfectados.setText("" + Ingles[9]);
        Ingles[10] = "Identificacion:";lblIdentificacion.setText("" + Ingles[10]);
        //botones de requerimientos
        Ingles[11] = "Nuevo:";btnNuevoR.setText("" + Ingles[11]);
        Ingles[12] = "Guardar:";btnGuardar.setText("" + Ingles[12]);
        Ingles[13] = "Actualizar:";btnActualizar.setText("" + Ingles[13]);
        Ingles[14] = "Buscar:";btnBuscar.setText("" + Ingles[14]);
        //labels de ayuda
        Ingles[15] = "Codigo:";lblCode.setText("" + Ingles[15]);
        Ingles[16] = "Tipo de ayuda:";lblTipoAyuda.setText("" + Ingles[16]);
        Ingles[17] = "Fecha:";lblFecha.setText("" + Ingles[17]);
        //botones de ayuda
        Ingles[18] = "Nuevo:";btnNewA.setText("" + Ingles[18]);
        Ingles[19] = "Guardar:";btnSaveA.setText("" + Ingles[19]);
        Ingles[20] = "Registro afectados ola invernal.";lblRegistro.setText("" + Ingles[20]);
        Ingles[21] = "Requerimientos";lblRequerimientos.setText("" + Ingles[21]);
        //cambiar combobox
        cbxIdioma.setModel(new DefaultComboBoxModel<>(new String [] {"Elige un idioma","1.Español","2.Ingles"}));
        cbxSexoR.setModel(new DefaultComboBoxModel<>(new String [] {"Elige una opcion","1.Hombre","2.Mujer"}));
        cbxTipoAyudaA.setModel(new DefaultComboBoxModel<>(new String [] {"Seleccione una ayuda","1.Comida","2.Aseo"
        ,"3.Electrodomesticos","4.Monetario"}));
        cbxIdioma.setSelectedIndex(0);
        }
    }//GEN-LAST:event_btnCambiarIdiomaActionPerformed

    // seccion de ayudas
    
    private void btnNewAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewAActionPerformed
        txtItemA.setText("");
        txtCodeA.setText("");
        cbxTipoAyudaA.setSelectedIndex(0);
        lblColocarFecha.setText(""+fecha);
        fnt_aleatorio2(1,10000);
        fnt_aleatorio(1, 10000);
    }//GEN-LAST:event_btnNewAActionPerformed
private void fnt_Guardar( String codigo){
    int contador = 0;
        for(int i = 0; i < fila; i++){
            if(codigo.equals(Ayudas[i][1])){
                contador++;
            }
        }
        if(contador == 3){
            if(cbxIdioma.getSelectedIndex()==0){
                lblMensajeAyudas.setText("Has agotado todas tus ayudas");
            }
            if(cbxIdioma.getSelectedIndex()==1){
                lblMensajeAyudas.setText("You have exhausted all your aid");
            }
        }else{
            Ayudas[fila][0] = txtItemA.getText();
            Ayudas[fila][1] = codigo;
            Ayudas[fila][2] = lblColocarFecha.getText();
            Ayudas[fila][3] = cbxTipoAyudaA.getSelectedItem().toString();
            fila++;
            if(cbxIdioma.getSelectedIndex()==1){
                JOptionPane.showMessageDialog(null, "Registro éxitoso");
            }
            if(cbxIdioma.getSelectedIndex()==2){
                JOptionPane.showMessageDialog(null, "nice");
            }
        }
    }
    private void btnSaveAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveAActionPerformed
        fnt_Guardar(txtCodeA.getText());
    }//GEN-LAST:event_btnSaveAActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
    if (txtCantHabitR.getText().equals("")||txtContactoR.getText().equals("")||txtCorreoR.getText().equals("")){
            if(cbxIdioma.getSelectedIndex() == 0){
                JOptionPane.showConfirmDialog(null, "Debe ingresar la informacion solicitada");
            }
            if(cbxIdioma.getSelectedIndex() == 1){
                JOptionPane.showMessageDialog(null, "You must enter the requested information");
            }
        }else{
             for (int i = 0; i <afectados.size(); i++){
            if (txtIdentificacionR.getText().equals(afectados.get(i).getId())){
               sw= 1;
               encuentra = i;
            }
        }
        if (sw == 0){
            afectados.get(encuentra).setIntCantHabitantes(Integer.parseInt(txtCantHabitR.getText()));
        afectados.get(encuentra).setStrContacto(txtContactoR.getText());
        afectados.get(encuentra).setStrcorreo(txtCorreoR.getText());
        if(cbxIdioma.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(null, "Información actualizada con exito");
        }
        if(cbxIdioma.getSelectedIndex()==1){
            JOptionPane.showMessageDialog(null,"Successfully updated information");
                }
            }
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void cbxIdiomaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbxIdiomaKeyReleased
        //Aclaracion: guarde las traducciones en los vectores incorrectos y me dio pereza cambiarlos :V
    }//GEN-LAST:event_cbxIdiomaKeyReleased

    private void cbxIdiomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxIdiomaActionPerformed
           //Aclaracion: guarde las traducciones en los vectores incorrectos y me dio pereza cambiarlos :V
    }//GEN-LAST:event_cbxIdiomaActionPerformed

    private void txtItemAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtItemAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtItemAActionPerformed

       
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCambiarIdioma;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNewA;
    private javax.swing.JButton btnNuevoR;
    private javax.swing.JButton btnSaveA;
    private javax.swing.JComboBox<String> cbxIdioma;
    private javax.swing.JComboBox<String> cbxSexoR;
    private javax.swing.JComboBox<String> cbxTipoAyudaA;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lblAfectacion;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblAyudas;
    private javax.swing.JLabel lblBarrio;
    private javax.swing.JLabel lblCantAfectados;
    private javax.swing.JLabel lblCode;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblCodigoR;
    private javax.swing.JLabel lblColocarFecha;
    private javax.swing.JLabel lblContacto;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblIdentificacion;
    private javax.swing.JLabel lblItem;
    private javax.swing.JLabel lblMensajeAyudas;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblRegistro;
    private javax.swing.JLabel lblRequerimientos;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblTipoAyuda;
    private javax.swing.JTextField txtAfectacionR;
    private javax.swing.JTextField txtApellidoR;
    private javax.swing.JTextField txtBarrioR;
    private javax.swing.JTextField txtCantHabitR;
    private javax.swing.JTextField txtCodeA;
    private javax.swing.JTextField txtContactoR;
    private javax.swing.JTextField txtCorreoR;
    private javax.swing.JTextField txtEdadR;
    private javax.swing.JTextField txtIdentificacionR;
    private javax.swing.JTextField txtItemA;
    private javax.swing.JTextField txtNombreR;
    // End of variables declaration//GEN-END:variables
}
